server:
  port: 8002
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      platform: h2
      schema-locations: classpath:schema.sql
      mode: always
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: debug