auth-server: http://peer2:8001/auth
resource-server: http://peer3:8002/resource1
server:
  port: 8011
spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          spirit:
            client-id: SpiritClient
            client-secret: 1qaz2wsx
            client-name: Spirit 客户端
            authorization-grant-type: authorization_code
            scope: book,read
            redirect-uri: http://peer1:8011/login/oauth2/code/spirit
            provider: spirit
        provider:
          spirit:
            authorization-uri: ${auth-server}/oauth/authorize
            token-uri: ${auth-server}/oauth/token
            user-info-uri: ${auth-server}/user/me
            user-name-attribute: name
      
                 
debug: true