server:
  port: 8004
  
webflux-jwt:
  password:
    encoder:
      secret: mysecret
      iteration: 33
      keylength: 256
  jjwt:
    secret: jjwtsecret1234567890qwertyuiopasdfghjklzxcvbnm1qaz2wsx3edc4rfv5tgb6yhn7ujm8ik,9ol.0p;/
    expiration: 3600
    
logging:
  level:
    root: INFO
